
path: /home/bg9287/object_detection

train: images/train
val: images/validation
test: images/test

names:
    0: Zero
    1: One
    2: Two
    3: Three
    4: Four
    5: Five
    6: Six
    7: Seven